import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="6nvi4s1">
            <body className="antialiased" data-oid="g6y.kn_">
                {children}
            </body>
        </html>
    );
}
