import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="lenw:pg">
            <body className="antialiased" data-oid="z73l6lt">
                {children}
            </body>
        </html>
    );
}
